name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt

    - name: Run docker
      run: |
        pytest pytestt.py

    - name: Run tests
      run: |
        echo "\nFROM python:3.9\nRUN apt-get update\nRUN apt-get install -y git\nRUN git clone https://github.com/kurap1ka00/resource-analyzer.git\nWORKDIR /resource-analyzer\nRUN pip install -r requirements.txt\nCMD ["python3", "./main.py"]">/Dockerfile

        docker build -t my-resource-analyzer $PWD
      
        docker run -it my-resource-analyzer
          