name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt

    - name: Run docker
      run: |
        pytest pytestt.py

    - name: Run tests
      run: |
        
        docker build -t my-resource-analyzer $PWD/resource-analyzer/
      
        docker run -t my-resource-analyzer
          